server:
  port: 9411
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: microservice-zipkin-server

  # 链接rabbitmq
  rabbitmq:
    host: 192.168.10.61
    port: 5672
    username: root
    password: kshop

  sleuth:
    enabled: false
    sampler:
      percentage: 1


zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      cluster: dashabi
      hosts: http://10.10.7.208:9200
      index: zipkin
      index-shards: 5
      index-replicas: 1
      date-separator: '-'

http.cors.enabled: true
http.cors.allow-origin: "*"

management:
  security:
    enabled: false





#日志
logging:
  level:
    root: info
    java.sql: debug
    com.apache.ibatis: debug
    com.emotte.cloud.**.mapper: debug
    com.emotte.cloud.mapper: debug
    org.springframework.cloud.sleuth: DEBUG
    # org.springframework.web: debug
    org.springframework.web.servlet.DispatcherServlet: debug


